### ISSUE TITLE
Adopt representation api 

### ISSUE THREAD

**Issue by VanyaDNDZ** [LialinMaxim/SSkey#56]
Flask-RESTful has a cool feature https://flask-restful.readthedocs.io/en/latest/extending.html#response-formats. 

Please re-write all the places where 
`headers = {'Access-Control-Allow-Origin': '*'} ` 
or 
`return {'message': msg}, status, {'Access-Control-Allow-Origin': '*'} ` 

are used.

**Comment by ArturM94** [comment]
@VanyaDNDZ 
For example /home route was:
```
class Home(Resource):
    def get(self):
        return {'message': 'Home Page'}, 200, {'Access-Control-Allow-Origin': '*'}
```
In browser view:
```
{
    "message": "Home Page"
}
```
---
And now:
```
headers = {'Access-Control-Allow-Origin': '*'}


@api.representation('/json')
class Home(Resource):
    def get(self):
        message = 'Representation Home Page'
        status = 200
        return message, status, headers
```
In browser view:
```
"Representation Home Page"
```

**Comment by ArturM94** [comment]
Done.
